name: Release
on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code.
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Get CMake.
        uses: lukka/get-cmake@latest

      - name: Restore artifacts or run vcpkg.
        uses: lukka/run-vcpkg@v10.2

      - name: Run CMake using CMakePreset.json and vcpkg.json.
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'release'
          buildPreset: 'release'

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: cmake --preset=release -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    
      - name: Test
        working-directory: ${{github.workspace}}/build
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: Create Package
        run: |
          zip -r -db ${{github.workspace}}/zenzizenzizenzic-${{ runner.os }} build/zenzizenzizenzic_ncurses build/data/ build/README.md build/LICENSE

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{github.workspace}}/zenzizenzizenzic-${{ runner.os }}.zip